<?php
/**
 * Sri Siddaroodha Swamiji Ashrama Theme Functions.
 */

if ( ! function_exists( 'sriaaroodha_theme_setup' ) ) :
	function sriaaroodha_theme_setup() {
		// Add default posts and comments RSS feed links to head.
		add_theme_support( 'automatic-feed-links' );

		// Let WordPress manage the document title.
		add_theme_support( 'title-tag' );

		// Enable support for Post Thumbnails on posts and pages.
		add_theme_support( 'post-thumbnails' );

		// Register Main Menu
		register_nav_menus( array(
			'primary' => esc_html__( 'Primary Menu', 'sriaaroodha-theme' ),
		) );
	}
endif;
add_action( 'after_setup_theme', 'sriaaroodha_theme_setup' );

/**
 * Enqueue scripts and styles.
 */
function sriaaroodha_scripts() {
	// Enqueue the main stylesheet generated by Tailwind
	wp_enqueue_style( 'sriaaroodha-style', get_template_directory_uri() . '/assets/main.css', array(), '1.0.0' );

	// Enqueue base style.css for metadata
	wp_enqueue_style( 'sriaaroodha-base-style', get_stylesheet_uri() );

	// Enqueue script if needed (currently static)
	// wp_enqueue_script( 'sriaaroodha-script', get_template_directory_uri() . '/assets/main.js', array(), '1.0.0', true );
}
add_action( 'wp_enqueue_scripts', 'sriaaroodha_scripts' );
